const express = require('express');
const questions = require('../routes/questions');
const topics = require('../routes/topics');
const cards = require('../routes/cards');
const users = require('../routes/users');
const avatars = require('../routes/avatars');
const videos = require('../routes/videos');
const cardends = require('../routes/cardends');
const challengeends = require('../routes/challengeends');
// const restQuestions = require("../rest/rest_questions/21_21/21_21_11/21_21_11");
// const restful = require("../routes/restful");
// const rests = require("../routes/rests/rests");
// const settings = require("../routes/settings");
const auth = require('../routes/auth');
const error = require('../middleware/error');

module.exports = function (app) {
  app.use(express.json());
  app.use('/api/questions', questions);
  app.use('/api/topics', topics);
  app.use('/api/cards', cards);
  app.use('/api/users', users);
  app.use('/api/avatars', avatars);
  app.use('/api/videos', videos);
  app.use('/api/cardends', cardends);
  app.use('/api/challengeends', challengeends);
  // app.use("/api/restquestions", restQuestions);
  // app.use("/api/restful", restful);
  // app.use("/api/rests", rests);
  // app.use("/api/settings", settings);
  app.use('/api/auth', auth);
  app.use(error);
};
