@localhost = http://localhost:3000
@heroku = mathsnatch.herokuapp.com

@user_id = 600347eec80f482fa82b7d46
# login user and delete guest account   /api/auth/:user_id
POST {{localhost}}/api/auth/{{user_id}}
content-type: application/json
accept: application/json

{
  "email": "oguzcc@mathsnatch.com",
  "password": "123456"
}