@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAzNDU2ZmM4MGY0ODJmYTgyYjdkNDMiLCJuYW1lIjoib2d1emNjIiwiZW1haWwiOiJvZ3V6Y2NAbWF0aHNuYXRjaC5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0dvbGQiOnRydWUsImlhdCI6MTYxMDgyNzM1Nn0.Vd9FW7b09M82S0PbJdldTmj6mpxlZ21gu2g-UgWsZd8
@localhost = http://localhost:3000
@heroku = mathsnatch.herokuapp.com


# get all avatars   /api/avatars
GET {{localhost}}/api/avatars
x-auth-token: {{token}}
content-type: application/json
accept: application/json