# get topics   /api/topics

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAzNDc1MGM4MGY0ODJmYTgyYjdkNDUiLCJuYW1lIjoib2d1emNjIiwiZW1haWwiOiJvZ3V6Y2NAbWF0aHNuYXRjaC5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0dvbGQiOnRydWUsImlhdCI6MTYxMDgyNzc5M30.t31Y92FrVm53fx-1Rj5W3eboRqVvPWzov1_vwkWGc5g
@localhost = http://localhost:3000
@heroku = mathsnatch.herokuapp.com

# get all topics   /api/topics
GET {{localhost}}/api/topics
x-auth-token: {{token}}
content-type: application/json
accept: application/json
