### videos post
### 
@topicId = 221
@cardId = 11
@videoId = {{topicId}}{{cardId}}
@questionId = {{videoId}}

@finish = 9999999

@question = <svg viewBox='0 0 64 64'><text x='32' y='40' text-anchor='middle' font-size='32' fill='#FFFFFF' font-family='RobotoMono'>4-(+8-1)</text></svg>
@correct = <svg viewBox='0 0 64 64'><text x='32' y='40' text-anchor='middle' font-size='32' fill='#FFFFFF' font-family='RobotoMono'>-3</text></svg>
@wrong = <svg viewBox='0 0 64 64'><text x='32' y='40' text-anchor='middle' font-size='32' fill='#FFFFFF' font-family='RobotoMono'>-4</text></svg>


@font_family = RobotoMono
@font_size = 32
@font_color = #FFFFFF

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmNhMGQxZmVlYTc5MTFlY2MxMGExZWIiLCJuYW1lIjoib2d1emNjMiIsImVtYWlsIjoib2d1emNjMkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpc0dvbGQiOnRydWUsImlhdCI6MTYwNzA4MjcxOH0.Y1u5bhXj9eBDlrvwHznUeaQLl92pZjF_HFOnf4Q2RT8

@a = <svg viewBox='0 0 64 64'><text x='32' y='40' text-anchor='middle' font-size='32' fill='{{font_color}}' font-family='RobotoMono'>
@a_end = </text></svg>

@begin = <svg viewBox='0 0 64 64'>


###
PUT http://localhost:3000/api/rests/{{topicId}}/{{cardId}}
x-auth-token: {{token}}
content-type: application/json
accept: application/json

{
	"restVideos": [
		{
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}11",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            "correctVideoId": "{{videoId}}21",
            "wrongVideoId": "{{videoId}}13",
            "questions": [
                {
                    "questionId": "{{questionId}}1101",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}13",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            "correctVideoId": "{{videoId}}21",
            "wrongVideoId": "{{videoId}}15",
            "questions": [
                { 
                    "questionId": "{{questionId}}1301",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}15",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
            "correctVideoId": "{{videoId}}21",
            "wrongVideoId": "{{videoId}}11",
            "questions": [
                { 
                    "questionId": "{{questionId}}1501",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}21",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
            "correctVideoId": "{{videoId}}31",
            "wrongVideoId": "{{videoId}}23",
            "questions": [
                { 
                    "questionId": "{{questionId}}2101",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}23",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
            "correctVideoId": "{{videoId}}31",
            "wrongVideoId": "{{videoId}}25",
            "questions": [
                { 
                    "questionId": "{{questionId}}2301",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}25",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
            "correctVideoId": "{{videoId}}31",
            "wrongVideoId": "{{videoId}}21",
            "questions": [
                { 
                    "questionId": "{{questionId}}2501",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}31",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            "correctVideoId": "{{finish}}",
            "wrongVideoId": "{{videoId}}33",
            "questions": [
                { 
                    "questionId": "{{questionId}}3101",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}33",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            "correctVideoId": "{{finish}}",
            "wrongVideoId": "{{videoId}}35",
            "questions": [
                { 
                    "questionId": "{{questionId}}3301",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    },
        {
            "topicId": "{{topicId}}", "cardId": "{{cardId}}", "videoId": "{{videoId}}35",
            "videoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            "solutionVideoLink": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            "correctVideoId": "{{finish}}",
            "wrongVideoId": "{{videoId}}31",
            "questions": [
                { 
                    "questionId": "{{questionId}}3501",
                    "question": "{{question}}",
                    "correctAnswer": "{{correct}}",
                    "wrongAnswer": "{{wrong}}"
                }
            ]
	    }
    ]
}